type Project {
    id: ID!
    name: String!
    description: String
    tasks: [Task!]!
    members: [Dev!]!
}

type Task {
    id: ID!
    title: String!
    description: String
    status: TaskStatus!
    project: Project!
    dev: Dev
}

type Dev {
    id: ID!
    name: String!
    email: String!
}

enum TaskStatus {
    UNASSIGNED
    TODO
    IN_PROGRESS
    DONE
}

type Mutation {
    createProject(name: String!, description: String): Project!
    deleteProject(id: ID!): Boolean!
    createTask(projectId: ID!, title: String!, description: String): Task!
    updateTaskStatus(taskId: ID!, status: TaskStatus!): Task!
}

type Query {
    project(id: ID!): Project
    projects: [Project!]!
    tasksByStatus(status: TaskStatus!): [Task!]!
    tasksByProject(id:ID!):[Task!]!
    taskById(id:ID!):Task
    devById(id:ID!):Dev
    devs: [Dev!]!
}